### ISSUE TITLE
Which platforms does this support?

### ISSUE THREAD

**Issue by killercup** [rust-cli/clap-permission-flag#1]
This is a 🔦 question.

Which platforms does this support? Does it do anything useful on Windows, for example?

As I can only assume other people are wondering this, too, it might be a good idea to answer this question in the Readme.

**Comment by yoshuawuyts** [comment]
haha, was about to open an issue about this. Right now it's `*nix` platforms only; compilation will straight up fail on other platforms (see https://travis-ci.org/yoshuawuyts/github-templates/jobs/418757028).

Agree we should put a note about this in the README.

**Comment by yoshuawuyts** [comment]
Now also compiles on Windows!
